CREATE TABLE IF NOT EXISTS `frigate_events` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `box` text DEFAULT NULL,
    `camera` text DEFAULT NULL,
    `data` text DEFAULT NULL,
    `startTime` datetime,
    `endTime` datetime,
    `false_positive` text DEFAULT NULL,
    `hasClip` tinyint(1),
    `hasSnapshot` tinyint(1),
    `event_id` text DEFAULT NULL,
    `label` text DEFAULT NULL,
    `plusId` text DEFAULT NULL,
    `retain` text DEFAULT NULL,
    `subLabel` text DEFAULT NULL,
    `thumbnail` text DEFAULT NULL,
    `topScore` text DEFAULT NULL,
    `zones` text DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;